# Generated by Django 6.0 on 2025-12-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matriculas')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
